### PR TITLE
Introduce carpets handling

### PR DESCRIPTION
**Pull request by rospogrigio**
And this PR introduces the handling of carpet map and no_carpet areas.
Here is how they appear on HA; 
map_image_roborock vacuum a15

... and here is on the Mi Home app (no_carpet area is not visible here):
mi home

Enjoy!

### CODE REVIEW

**Comment by rospogrigio** [comment]
OK fixed the conflicts, and updated the README as well. This PR must be merged on top of #356, that comes first.

**Comment by Nezz** [comment]
@rospogrigio I found a performance issue with the carpet drawing. I have a fix for it here:
https://github.com/humbertogontijo/homeassistant-roborock/pull/111

**Comment by rospogrigio** [comment]
Thank you @Nezz for the suggestion! I'm commiting the new code.

**Comment by PiotrMachowski** [comment]
Thank you, @rospogrigio!

**Pull request merged**
