### PR TITLE
Fix DeprecationWarning and aligned to HA v2012.12.0

### LINKED ISSUE #196: Beta 2021.12.0b0 Error
Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) implements device_state_attributes. Please report it to the custom component author.

### PR DESCRIPTION
**Pull request by elad-bar**
Fixed #196 - Beta 2021.12.0b0 Error
Changed in `camera.py` function `device_state_attributes` to `extra_state_attributes` as required in HA v2012.12.0 onwards

### CODE REVIEW

**Comment by elad-bar** [comment]
Added also:
- pre-commit
- cleaned references of import
- height and width to camera image function in camera.py (requried since few HA version's back)
- .gitignore

**Comment by Wibias** [comment]
Changed it on local server. Works just fine.

**Comment by Wibias** [comment]
Actually, excpet this error.

```
2021-12-25 12:59:14 ERROR (MainThread) [homeassistant.config] Platform error: camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 887, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 25, in <module>
    from .xiaomi.vacuum import XiaomiVacuum
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi/vacuum.py", line 3, in <module>
    from .common.map_data import MapData
ModuleNotFoundError: No module named 'custom_components.xiaomi_cloud_map_extractor.xiaomi.common'
```

**Comment by PiotrMachowski** [comment]
Thanks @elad-bar , but this pull request contains changes that break the integration (imports) or have already been fixed (deprecated code)

**Pull request closed without merging**
