### PR TITLE
Add option to save camera image to specified path

### PR DESCRIPTION
**Pull request by DirkFust**

### CODE REVIEW

**Comment by DirkFust** [comment]
Add an option ("snapshot_path") to the camera. 
If the option is set to a valid path, an image of the camera is saved there.

Use case: 
I use Telegram to get notifications for my vacuum, and I wanted to include an image of the cleaned area to the notification for a finished cleaning run. Hence, I needed an image file to attach to the notification.

**Comment by PiotrMachowski** [comment]
Hi,
Thanks for your contribution, but this feature is already supported by HA itself: [camera.snapshot](https://www.home-assistant.io/integrations/camera/#service-snapshot). Does your version add any additional functionality?

**Comment by DirkFust** [comment]
No, it does not. 
I should guessed that this is possible already. Thanks for the heads up!

**Comment by PiotrMachowski** [comment]
No problem :)

**Pull request closed without merging**
