### PR TITLE
Dreame support

### PR DESCRIPTION
**Pull request by PiotrMachowski**
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/pull/230#issuecomment-1023648748

### CODE REVIEW

**Comment by Neonox31** [comment]
- [ ] task 1
- [ ] task 2

**Comment by Neonox31** [comment]
Hello @PiotrMachowski,

Am I supposed to have the rights to push in the `dreame_support` branch ?

**Comment by PiotrMachowski** [comment]
@Neonox31 I'll check if it's possible, right now you have to create a PR to this branch

**Comment by Neonox31** [comment]
@PiotrMachowski Did you have a map with virtual walls and no mop areas ?
I added support for both features but my current map has not anyone of these.

**Comment by PiotrMachowski** [comment]
@Neonox31 I have many maps, so I think there might be some with these elements. I'm not able to check it now though

**Comment by auanasgheps** [comment]
@Neonox31 my map has a virtual wall and no mop area. I can send it if you need to test.

**Comment by Neonox31** [comment]
> @Neonox31 my map has a virtual wall and no mop area. I can send it if you need to test. (Dreame L10 Pro)

Yes, this will help me greatly, thank you!

**Comment by simonbuerger** [comment]
@Neonox31 I sent you mine on Twitter, also has virtual wall and no mop zone

**Comment by Neonox31** [comment]
@PiotrMachowski The regular map seems reflect only the last cleaning surface, for example the actual regular map of my vacuum is this one :
image
Because it has started and returned directly to the charger, so the image has a width of 23 px and a height of 8 px.

Did you experienced a similar behavior with other models ?

**Comment by PiotrMachowski** [comment]
@Neonox31 Something similar happens in Xiaomi API when the map is regenerated, but there are big margins around, so output map is not as small

**Comment by auanasgheps** [comment]
> > @Neonox31 my map has a virtual wall and no mop area. I can send it if you need to test. (Dreame L10 Pro)
> 
> @auanasgheps Yes, this will help me greatly, thank you!

Sure tell me how can I send it to you :)

**Comment by PiotrMachowski** [comment]
@Neonox31 I have added support for multiple paths and adjusted dreame parser to use it correctly, you can update your fork to include my changes.

By the way, do you have an account on HA forum? If so, please send me a message: [my profile](https://community.home-assistant.io/u/3_14)

**Comment by Neonox31** [comment]
> > > @Neonox31 my map has a virtual wall and no mop area. I can send it if you need to test. (Dreame L10 Pro)
> > 
> > 
> > @auanasgheps Yes, this will help me greatly, thank you!
> 
> Sure tell me how can I send it to you :)

Can you send it to dreame-maps@neonox31.anonaddy.me please ? Thanks !

**Comment by Neonox31** [comment]
> @Neonox31 I have added support for multiple paths and adjusted dreame parser to use it correctly, you can update your fork to include my changes.
> 
> By the way, do you have an account on HA forum? If so, please send me a message: [my profile](https://community.home-assistant.io/u/3_14)

Thanks for the multiple paths support, it works like a charm :
image

Direct message sent on H.A forum.

**Comment by auanasgheps** [comment]
> > > > @Neonox31 my map has a virtual wall and no mop area. I can send it if you need to test. (Dreame L10 Pro)
> > > 
> > > 
> > > @auanasgheps Yes, this will help me greatly, thank you!
> > 
> > 
> > Sure tell me how can I send it to you :)
> 
> Can you send it to [dreame-maps@neonox31.anonaddy.me](mailto:dreame-maps@neonox31.anonaddy.me) please ? Thanks !

Done, check your inbox :)

**Comment by Neonox31** [comment]
I added virtual walls and no mop areas support on my fork and it seems working !
image
Thanks to those who sent me their maps, this one helped me a lot :+1:

**Comment by Neonox31** [comment]
Hello 👋

I haven't given up don't worry.
I haven't few time to work on it last days and I'm struggling with room parsing :
image

I am not far from a solution 👍

**Comment by Hootie81** [comment]
This is great news, are we far away from getting a beta version on HACS? really keen to try it out.

**Comment by PiotrMachowski** [comment]
I have a lot of maps to test, so I think beta version won't be necessary ;)

**Comment by nirkons** [comment]
thanks guys, much appreciated

**Comment by PiotrMachowski** [comment]
@Neonox31 any progress here?
(please do not resolve conflicts, I will handle it)

**Comment by Neonox31** [comment]
@PiotrMachowski No more progress for the moment, I need to find some time to find a way to merge correctly the images of each map (regular & RISM)

**Comment by PiotrMachowski** [comment]
@Neonox31 No problem, take your time 👍
in the meantime (after tests) I will merge `dev` branch to `dreame_support`

**Comment by pergolafabio** [comment]
Is there already a way to test? Or not ready to test yet?

**Comment by PiotrMachowski** [comment]
@pergolafabio you can test it by manually installing version from `dreame_support` branch

**Comment by pergolafabio** [comment]
Perfect, will do it later...

So what's holding up to release then?

**Comment by PiotrMachowski** [comment]
@pergolafabio it's not fully finished

**Comment by pergolafabio** [comment]
i wanted to test, so loaded the branch, but get error below

```
2022-02-22 09:34:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.dreame fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 267, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 324, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
    return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 51, in decode_map
    return MapDataParserDreame.parse(unzipped, colors, drawables, texts, sizes, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 76, in parse
    map_data.image = MapDataParserDreame.parse_image(image_raw, header, colors, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 146, in parse_image
    image = ImageHandlerDreame.parse(image_raw, header, colors, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/image_handler.py", line 51, in parse
    pixels[x, y] = ImageHandler.__get_color__(COLOR_MAP_OUTSIDE, colors)
IndexError: image index out of range
```

This my config, a copy paste from roborock, offcourse changed token and IP

```
  - platform: xiaomi_cloud_map_extractor
    host: !secret dreame_ip
    token: !secret dreame_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    name: "Dreame"
    scan_interval: 15
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
    map_transformation:
      scale: 1
      rotate: 0
      trim:
        top: 20
        bottom: 20
        left: 10
        right: 10  
    attributes:
      - charger
      - image
      - map_name
      - obstacles
      - room_numbers
      - rooms
      - vacuum_position
      - walls
      - zones   
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
@pergolafabio current implementation returns only map from the last cleaning

**Comment by pergolafabio** [comment]
ok, that makes sense :-)

**Comment by eraycetinay** [comment]
tested and attached the ss.  works perfectly.  looking forward to the room maps.
Ekran Resmi 2022-03-06 07 30 21

**Comment by xBourner** [comment]
So i got a Dreame L10 Pro and installed the Branch.
It looks good for me but i wanted to trim the bottom red part of the map. This comes from a mirror and should not be seen in the card.

image

When i try to set it up with:

```
 map_transformation:
      scale: 2
      rotate: 90
      trim:
        top: 10
        bottom: 20
        left: 10
        right: 10
```

There is only this:

image

Does this comes from dreame branch or by the card itself?

**Comment by PiotrMachowski** [comment]
@xBourner Trimming doesn't work at this moment

**Comment by xBourner** [comment]
> @xBourner Trimming doesn't work at this moment

thank you for your fast reply. can you estimate when everything will work?
and is there anyway to help with this?

**Comment by PiotrMachowski** [comment]
@xBourner Implementation of this feature is done mostly by @Neonox31, I only do some little fixes and improvements. Right now the problem is to merge regular and RISM maps to make a complete map image. I also wait for version with rooms detection

**Comment by Neonox31** [comment]
Hi,

I am finally back with room support BUT : 
- My robot doesn't seems supporting room names and I do not took time to test them with other maps, I will try later
- @PiotrMachowski the two last `pos_x` and `pos_y` args for `Room` constructor seem to be dedicated to place the text of the name of the room but I confess to not knowing how to determine them, any idea ?

Here is a screen of the result on my map :
image

**Comment by PiotrMachowski** [comment]
@Neonox31 thank you so much! These fields are not mandatory, they can be just left empty

**Comment by Neonox31** [comment]
> @Neonox31 thank you so much! These fields are not mandatory, they can be just left empty

Yes, but if I let them empty, room names are never drawn not ?

**Comment by PiotrMachowski** [comment]
Yes, but drawing these names is supported only on small number of vacuums and it doesn't look so good anyway

**Comment by simonbuerger** [comment]
Thanks for working on this! I downloaded the latest from dreame support branch and ran into an error

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py:159
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 07:58:10 (186 occurrences)
Last logged: 08:13:46

Update for camera.xiaomi_cloud_map_extractor fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 267, in update
    self._handle_map_data(map_name)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 324, in _handle_map_data
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 36, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/vacuum.py", line 24, in decode_map
    return MapDataParserDreame.decode_map(raw_map_string, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 52, in decode_map
    return MapDataParserDreame.parse(unzipped, colors, drawables, texts, sizes, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 81, in parse
    rism_map_data = MapDataParserDreame.decode_map(
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 52, in decode_map
    return MapDataParserDreame.parse(unzipped, colors, drawables, texts, sizes, image_config, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 77, in parse
    map_data.image, map_data.rooms = MapDataParserDreame.parse_image(image_raw, header, colors, image_config, additional_data_json, map_data_type)
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 159, in parse_image
    room_names = {k: base64.decodebytes(v.get("name")) for (k, v) in additional_data_json["seg_inf"].items() if
  File "/config/custom_components/xiaomi_cloud_map_extractor/dreame/map_data_parser.py", line 159, in <dictcomp>
    room_names = {k: base64.decodebytes(v.get("name")) for (k, v) in additional_data_json["seg_inf"].items() if
  File "/usr/local/lib/python3.9/base64.py", line 537, in decodebytes
    _input_type_check(s)
  File "/usr/local/lib/python3.9/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

```

**Comment by Neonox31** [comment]
Hello @simonbuerger 

Thanks for your feedback, I used your map to fix the problem and it should works now !
FYI room names will never be drawn on the final map but are stored in `map_data.rooms`.

**Comment by xBourner** [comment]
hi i installed both changes and tried it. rooms are shown correct for me. but now i have an issue with the rotation of the map.

here is one witout rotation where nothing is rotated. 
Screenshot 2022-03-19 112231

and then one with rotation:

Screenshot 2022-03-19 112422

the map itself is not rotated like my no go zone. is this an issue of the new branch or am i doing something wrong?

**Comment by Neonox31** [comment]
Hello @xBourner ,

Good catch thanks, it should be fixed when https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/pull/265 will be merged 🙂

**Comment by PiotrMachowski** [comment]
Merged 👍

**Comment by Neonox31** [comment]
@PiotrMachowski I believe we are now ready to test the map pack, what do you think ?
On morning I tried to reuse `map_processor` script but I was no able to run it correctly, it ends with the following :
```
raceback (most recent call last):
  File "/config/map_processor.py", line 6, in <module>
    from custom_components.xiaomi_cloud_map_extractor.camera import PLATFORM_SCHEMA, VacuumCamera
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 18, in <module>
    from homeassistant.components.camera import Camera, ENTITY_ID_FORMAT, PLATFORM_SCHEMA, SUPPORT_ON_OFF
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 24, in <module>
    from homeassistant.components import websocket_api
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/__init__.py", line 12, in <module>
    from . import commands, connection, const, decorators, http, messages  # noqa: F401
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 25, in <module>
    from homeassistant.helpers import config_validation as cv, entity, template
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 45, in <module>
    from .entity_platform import EntityPlatform
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 15, in <module>
    from homeassistant import config_entries
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 17, in <module>
    from .components import persistent_notification
  File "/usr/src/homeassistant/homeassistant/components/persistent_notification/__init__.py", line 15, in <module>
    from homeassistant.helpers.entity import async_generate_entity_id
ImportError: cannot import name 'async_generate_entity_id' from partially initialized module 'homeassistant.helpers.entity' (most likely due to a circular import) (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```
Any idea ?

**Comment by PiotrMachowski** [comment]
@Neonox31 I think we can test ;)

Hmmm, it worked the last time I have tried to use it...

**Comment by Neonox31** [comment]
> @Neonox31 I think we can test ;)
> 
> Hmmm, it worked the last time I have tried to use it...

OK so I let you testing because after many attempts I was not able to resolve my issue with `map_processor` and I'm pretty it was working before.

**Comment by PiotrMachowski** [comment]
No problem, I will check it out today/tomorrow

**Comment by inviz-ize** [comment]
Screenshot 2022-03-21 at 11 53 32
works perfect for me!

**Comment by PiotrMachowski** [comment]
@Neonox31 It still works just fine on my PC. Soooooo what's left to do?

**Comment by PiotrMachowski** [comment]
@Neonox31 I have merged changes from `dev` branch to this PR, so there are quite a few new changes here

**Comment by Neonox31** [comment]
> @Neonox31 It still works just fine on my PC.
> 
> Soooooo is there anything left to do (except for final touches, documentation and final tests)?

Nice ! Everything OK on my side, let's go for final touches 😏

**Comment by pergolafabio** [comment]
Nice job guys!

**Comment by PiotrMachowski** [comment]
> > @Neonox31 It still works just fine on my PC.
> > Soooooo is there anything left to do (except for final touches, documentation and final tests)?
> 
> Nice ! Everything OK on my side, let's go for final touches 😏

**Comment by aviadlevy** [comment]
Hi, any update on this long awaited MR? 
I think we all eager to start use it to beautify our dashboards

Seems like 20 days ago we were on the verge of merging it but no update since

Thanks and I'm very appreciate your effort

**Comment by Neonox31** [comment]
Hi @PiotrMachowski 

Can I help on something to help this P.R merged ?

**Comment by PiotrMachowski** [comment]
Hi @Neonox31!
I have a fire in another repo that needs to be put out :confused: please give me some time

**Comment by Neonox31** [comment]
> Hi @Neonox31! I have a fire in another repo that needs to be put out confused please give me some time

No problem, I was just trying to find out if I could help 👍
Good luck with the other repo.

**Pull request merged**
