### PR TITLE
Add support for local valuetdo vacuums

### PR DESCRIPTION
**Pull request by tobi1449**
This PR adds the ability to use valetudo robots as source for map data instead of the Xiaomi cloud.
It accepts a valetudo camera entity and extracts the map data from the camera's image.

Implemented and working:

- Drawing rooms and walls
- Drawing map objects (vacuum, charger, zones, ...)
- Drawing the vacuum's path

Open TODOs:

- [ ] Trimming does not work correctly, the map is trimmed but the map objects are positioned wrongly
- [ ] Scaling does not work correctly, the map is scaled but the map objects are positioned wrongly
- [x] Image generation performance, using Numpy sped things up greatly

### CODE REVIEW

**Comment by sca075** [comment]
I found a method to generate the image without using Nunpy.. I use the PIL Draw instance and it works fine. 
Layer one (empty new pill image max_x, max_y), save, draw the flour (layer 1), daw the walls (layer 2) and then path, robot and changer (layer 3) total run time 0:00:04.475454 per json that is similar to Numpy (that I try too and.. it is a pain to keep it at centre :) how can I upload the code I made for your evaluation?

**Comment by PiotrMachowski** [comment]
> I found a method to generate the image without using Nunpy.. I use the PIL Draw instance and it works fine.

This is the same as current implementation of Map Extractor. I have to check if numpy approach is faster

**Comment by sca075** [comment]
I do have some code also with Numpy, just please confirm, is the json coming from MQTT or from the query to the Valetudo api.. something like.. 'http://valetudo-myvacuum.local/api/v2/robot/state/map ? Will check my code with Numpy and share it to you..

**Comment by sca075** [comment]
`import datetime
import json
import numpy as np
from PIL import Image
from PIL import ImageDraw

#area = 332400
#pixel_count = 13296
new_json = ""
old_json = ""
path_color = (192, 192, 192)
floor_color = (0, 255, 255)
walls_color = (255, 255, 0)
robot_color = (254, 254, 254)
charger_color = (0, 128, 0)


# Create a sublist N elements from a list with mixed values
def sublist(lst, n):
    sub = []; result = []
    for ni in lst:
        sub += [ni]
        if len(sub) == n:
            result += [sub]; sub = []
    if sub:
        result += [sub]
    return result


# Load the Jason response
with open("data1.json") as user_file:
    parsed_json = json.load(user_file)
start = datetime.datetime.now()
# Extract from the Valetudo Jason the relevant data.
floor_pixel = parsed_json["layers"][0]["compressedPixels"]
walls_pixel = parsed_json["layers"][1]["compressedPixels"]
path_pixels = parsed_json["entities"][0]["points"]
charger_pos = parsed_json["entities"][1]["points"]
robot_position = parsed_json["entities"][2]["points"]
# Calibration data of the result image
# Size X and Y give the result as calculated in the robot.
# Pixel size is defined for lidar resolution and image points location.
size_x = int(parsed_json["size"]["x"])
size_y = int(parsed_json["size"]["y"])
pixel_size = int(parsed_json["pixelSize"])
json_id = parsed_json["metaData"]["nonce"]


# Initialize Pixels arrays
floor_pixels = sublist(floor_pixel, 3)
walls_pixels = sublist(walls_pixel, 3)
#print(wall_pixel)
path_pixel = sublist(path_pixels, 2)
# print(path_pixel)
# print("charger: ", charger_pos, " robot position: ", robot_position)


# Initialize image with transparent background
img = Image.new('RGBA', (size_x, size_y), (0, 0, 0, 0))

# Center of the image
center_x = size_x // 2
center_y = size_y // 2

# Define two lists of pixel values
#list1 = [(center_x + x, center_y + y, n) for x, y, n in walls_pixels
#list2 = [(center_x + x, center_y + y, n) for x, y, n in floor_pixels
def from_json_to_image(data, pixel_size, color):
    # Create an array of zeros for the image
    image_array = np.zeros((5120, 5120, 3), dtype=np.uint8)

    # Draw rectangles for each point in data
    for x, y, z in data:
        for i in range(z):
            col = (x + i) * pixel_size
            row = y * pixel_size
            image_array[row:row+pixel_size, col:col+pixel_size] = color

    # Convert the image array to a PIL image
    return image_array

start_time = datetime.datetime.now()
layers = from_json_to_image(floor_pixels, pixel_size, floor_color)
layers = layers + from_json_to_image(walls_pixels, pixel_size, walls_color)
image = Image.fromarray(layers)
print(datetime.datetime.now()-start_time)
image.show()

`

**Comment by sca075** [comment]
hope this can help

**Comment by sca075** [comment]
```python

``` def from_json_to_image(data, pixel_size, color):
             image_array = np.zeros((5120, 5120, 3), dtype=np.uint8)
             for x, y, z in data:
                for i in range(z):
                     col = (x + i) * pixel_size
                     row = y * pixel_size
                    image_array[row:row+pixel_size, col:col+pixel_size] = color
      return image_array

**Comment by sca075** [comment]
The function above is the one that create the a Numpy array. You can then use that to create the Layer_flour, Layer_Walls, and ... tested this right now the process time is 0:00:00.565693 for both layers added to an image.
Not made yet the path..

layers = from_json_to_image(floor_pixels, pixel_size, floor_color)
layers = layers + from_json_to_image(walls_pixels, pixel_size, walls_color)
image = Image.fromarray(layers)

The list _pixel is a list of list [[520, 254, 7], [x, y, n] ...] 

Hope this helps

**Comment by tobi1449** [comment]
> > I found a method to generate the image without using Nunpy.. I use the PIL Draw instance and it works fine.
> 
> This is the same as current implementation of Map Extractor. I have to check if numpy approach is faster

It's much faster from what I've seen. As far as I could see that's also why it is generally recommended now over manually setting the pixels. 


> I do have some code also with Numpy, just please confirm, is the json coming from MQTT or from the query to the Valetudo api.. something like.. 'http://valetudo-myvacuum.local/api/v2/robot/state/map ? Will check my code with Numpy and share it to you.. and Ps. it work fast same as drawing (but we drawing we need to crop the image causing an offset between vacuum position and image centre / vacuum position).

The json is coming from the Valetudo vacuum encoded in the image published via MQTT.

**Comment by sca075** [comment]
> > > I found a method to generate the image without using Nunpy.. I use the PIL Draw instance and it works fine.
> > 
> > 
> > This is the same as current implementation of Map Extractor. I have to check if numpy approach is faster
> 
> It's much faster. As far as I could see that's also why it is generally recommended now over manually setting the pixels.
> 
> > I do have some code also with Numpy, just please confirm, is the json coming from MQTT or from the query to the Valetudo api.. something like.. 'http://valetudo-myvacuum.local/api/v2/robot/state/map ? Will check my code with Numpy and share it to you.. and Ps. it work fast same as drawing (but we drawing we need to crop the image causing an offset between vacuum position and image centre / vacuum position).
> 
> The json is coming from the Valetudo vacuum encoded in the image published via MQTT.

Thanks a lot for your replay, and yep, it Numpy is much faster than edit the image with PIL, and I saw also that CPU and Memory usage went down too.. I changed the array to 4 dimensions to get the full RGB value (RRR.GGG.BBB.STS) just playing now with the Path draw.. I guess via MQTT is better too.. but I´m currently not at home.. so.. no test done till now. Would anyhow contribute if needed.. thanks for the great job Guys.

**Comment by tobi1449** [comment]
> > > > I found a method to generate the image without using Nunpy.. I use the PIL Draw instance and it works fine.
> > > 
> > > 
> > > This is the same as current implementation of Map Extractor. I have to check if numpy approach is faster
> > 
> > 
> > It's much faster. As far as I could see that's also why it is generally recommended now over manually setting the pixels.
> > > I do have some code also with Numpy, just please confirm, is the json coming from MQTT or from the query to the Valetudo api.. something like.. 'http://valetudo-myvacuum.local/api/v2/robot/state/map ? Will check my code with Numpy and share it to you.. and Ps. it work fast same as drawing (but we drawing we need to crop the image causing an offset between vacuum position and image centre / vacuum position).
> > 
> > 
> > The json is coming from the Valetudo vacuum encoded in the image published via MQTT.
> 
> Thanks a lot for your replay, and yep, it Numpy is much faster than edit the image with PIL, and I saw also that CPU and Memory usage went down too.. I changed the array to 4 dimensions to get the full RGB value (RRR.GGG.BBB.STS) just playing now with the Path draw.. I guess via MQTT is better too.. but I´m currently not at home.. so.. no test done till now. Would anyhow contribute if needed.. thanks for the great job Guys.

Well there's (probably) not much left to do anyway. 
As I wrote in the PR description, what still needs some work are scaling and trimming, the calculation for the map objects' positions don't take that into account. 
The rest should be implemented.

**Comment by deam0n** [comment]
may i pay someone a beer to carry on this pr?

**Comment by PiotrMachowski** [comment]
@deam0n You can buy a beer to @tobi1449 for creating this PR. I plan work on this integration soon (I was working on the lovelace vacuum map card lately)

**Comment by sca075** [comment]
> @deam0n You can buy a beer to @tobi1449 for creating this PR. I plan to work on this integration soon (I was working on the lovelace vacuum map card lately)

We will do it for sure :) I just completed some experiment too on this matter.. and @PiotrMachowski  the new card was interfaced successfully from my side thanks to the super documentation you did on this well done component. If you don't mind I linked your project here https://github.com/sca075/valetudo_vacuum_mapper/tree/main

**Comment by phrozen77** [comment]
Quick question: if i understand the discussion so far correctly, this PR needs to be merged to be able to show the map of a "local-only" Valetudo Roborock S5 in "Lovelace Vacuum Map card", right?

**Comment by PiotrMachowski** [comment]
@phrozen77 you can check out this project
https://github.com/sca075/valetudo_vacuum_camera

**Comment by phrozen77** [comment]
> @phrozen77 you can check out this project https://github.com/sca075/valetudo_vacuum_camera

Found and tried it in the meanwhile - doesn't support external MQTT servers, sadly - thanks for the heads up!

**Comment by sca075** [comment]
@phrozen77 We will work on it.. keep an an eye open soon I hope we can support MQTT external servers ;) @PiotrMachowski Thanks once again for your super work ;)

**Comment by PiotrMachowski** [comment]
@sca075 now that I have found out about your component I don't know what to do with this PR... I wanted to merge it, but now I have also extracted map parsing to separate pypi packages, so I would have to do it for Valetudo as well

**Comment by sca075** [comment]
If there is anything I can do to help you out you can reach me also via discord. sandro0538 I can speak Polish too ;)

**Comment by sca075** [comment]
@PiotrMachowski In the end it was possible to fix the configuration issue reported by @phrozen77 I would say quite easily.  So it is really up to you, I think it is clear that your main aim is to support unrooted vacuums, the card is supporting already the Valetudo vacuums beautifully and it is a master peace also your extractor that I used for several years too. 
Point is that this isn't a competition.. not for me for instance. When I did start the development of the camera integration for the Valetudo vacuums it was just because understanding yours and @tobi1449  busy times I couldn't use most of the functionalities your card offers. With this, I guess just that there is a common understanding.. I don't do this for fame or incomes, but just.. once again, because I really appreciate the work you have done and you are continuously doing. Therefore no hard feeling whatever you will decide to do guys ;) as per the goal in the end is a common one.

**Comment by PiotrMachowski** [comment]
@sca075 I've sent you a message on Discord

**Comment by sca075** [comment]
@PiotrMachowski revived ;)

**Comment by tobi1449** [comment]
As something very similar has been implemented by @sca075 with [valetudo_vacuum_camera](https://github.com/sca075/valetudo_vacuum_camera), I will close this PR. 

Thanks @sca075 for your work 👍

**Pull request closed without merging**
