### PR TITLE
Adding support for saving map image in local storage

### PR DESCRIPTION
**Pull request by desout**
In my case of creating ffmpeg camera for streaming map in HomeKit, I create a possibility for saving image in system storage.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
It can be done with a built-in HA service `camera.snapshot`, is there any advantage in your approach?

**Comment by desout** [comment]
> It can be done with a built-in HA service `camera.snapshot`, is there any advantage in your approach?


It is not clear to me how to get an image from a snapshot. 
Am I missing something?
In any case, I think that this method provides the following advantages:
  - better resolution than getting this image from camera (due to size)
  - fewer file updates (because we know about all map updates)
  - no unnecessary synchronization between automation and your plugin
  - Removing another watchers (in case detecting changes in the file system)

**Comment by PiotrMachowski** [comment]
Snapshot saves an image for a camera, just your solution. Everything is described [here](https://www.home-assistant.io/integrations/camera/#service-snapshot). 
* The resolution should be exactly the same, because a snapshot is created using exactly the same data
* Actually this will result in more file updates, but they will be performed only when required (which is good)
* That's correct
* Actually both solutions don't require any file watchers

**Comment by desout** [comment]
Anyway, I think this feature can simplify this process. IMHO

**Comment by PiotrMachowski** [comment]
I think I can merge your changes, but they will be included in a next release (not in a dedicated one)

**Comment by desout** [comment]
> I think I can merge your changes, but they will be included in a next release (not in a dedicated one)

Perfect for me, I can use my fork until the release is ready

**Pull request merged**
