### PR TITLE
Viomi support

### PR DESCRIPTION
**Pull request by halfbakery**
This PR adds a preliminary support to the Viomi V2 Pro / STYJ02YM / etc vacuums. I'm an owner of a Viomi V2 Pro vacuum, so it's tested on that (but it should work on other models too). My test tool is the `get_map.py` script, I've never used in Home Assistant yet :-)

The following things has been tested:
- displaying the map is mostly functional
- displaying the previously cleaning route and area
- charging station position
- restricted areas and walls
- selected cleaning area
- current position

The following things must be fixed:
- figuring out the unknown map values (obstacles or selected rooms?)
- testing the goto position
- using map trimming relocates every object into a wrong position
- using room names read from the map

This time I left the refactoring to you: the ImageHandler class could be split into a device dependent / device independent part. At least rename the `parse()` method to `parse_roborock()` or similar. :-)

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
I have checked and v1 devices still work :)

**Comment by PiotrMachowski** [comment]
@halfbakery Can you check out the latest version? I have refactored whole component, added usage of room names and fixed map trimming. It should also work in HA for both V1 and V2

**Comment by HepoH3** [comment]
Tried to use this integration after the merge on my STYJ02YM vacuum. I have 1 error, and few warnings:

Now, it takes about 180-320 seconds to reboot server (it was 13s before).
In developer tools I can see that there is something:

But, if I try to use Lovelace Xiaomi Vacuum Map card, I can't see anything except mode part of the card:

camera config:
```
- platform: xiaomi_cloud_map_extractor
  name: vacuum_extractor_camera
  host: !secret kraken_ip
  token: !secret kraken_token
  username: !secret xiaomi_username
  password: !secret xiaomi_password
  draw: ['all']
  attributes:
    - calibration_points
```
card config:
```
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.kraken
    map_camera: camera.vacuum_extractor_camera
    camera_calibration: true
```
xiaomi credentials and vacuum ip/token are 100% valid, because I used them in other integrations and they are working.
Hope that will helps.

**Comment by HepoH3** [comment]
Oh, I used master branch instead of the dev_new_api.
Well, it's really similar except of dev tools:

server log:

it seems that STYJ02YM didn't recognized as v2 api device.

**Comment by HepoH3** [comment]
When I've added viomi.vacuum.v7 into V2_MODELS list, server started in 40s, now I have this error in the log:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 243, in update
    map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_vacuum.py", line 27, in get_map
    map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_vacuum_v2.py", line 25, in decode_map
    return MapDataParserV2.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser_v2.py", line 143, in parse
    MapDataParserV2.parse_section(buf, 'rooms', map_id)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser_v2.py", line 278, in parse_section
    raise ValueError(
ValueError: error parsing section rooms at offset 0x9c575: magic check failed 0x5f6db681
```
It seems that there is nothing I can do anymore :)

**Comment by PiotrMachowski** [comment]
@HepoH3 thank you for your tests! Can you enable map saving and send me your map file?

Config:
```
- platform: xiaomi_cloud_map_extractor
  name: vacuum_extractor_camera
  host: !secret kraken_ip
  token: !secret kraken_token
  username: !secret xiaomi_username
  password: !secret xiaomi_password
  draw: ['all']
  attributes:
    - calibration_points
  store_map: true
```
[Retrieving map file](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/89#issuecomment-851058398)

**Comment by HepoH3** [comment]
@PiotrMachowski Sure, if I done this correctly, that it is:

[tmp.zip](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/6596757/tmp.zip)

**Comment by PiotrMachowski** [comment]
@HepoH3 Is this map correct? 
image

**Comment by HepoH3** [comment]
> @HepoH3 Is this map correct?
> image

Yep.

**Comment by PiotrMachowski** [comment]
@HepoH3 you can download the latest version, it should work now

**Comment by HepoH3** [comment]
> 
> 
> @HepoH3 you can download the latest version, it should work now

I confirm that. It's work now. Apartment area pretty small, but I'm pretty sure I can fix it via card parameters.

**Comment by PiotrMachowski** [comment]
@HepoH3 [trimming](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration) should fix this issue :)

**Comment by HepoH3** [comment]
> 
> 
> @HepoH3 [trimming](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration) should fix this issue :)

Yup. Well, congrats for all of us, @halfbakery you're hero!
Thank you guys!

**Comment by halfbakery** [comment]
> @halfbakery Can you check out the latest version? I have refactored whole component, added usage of room names and fixed map trimming. It should also work in HA for both V1 and V2

Everything works fine. I've seen the trimming fix, I forgot that the image is stored upside down :-)

**Comment by HepoH3** [comment]
@PiotrMachowski I don't know would it been better to post it here, or create new issue in the card repo.
Map rendering just fine, but I can't make my vacuum doing it's job. It does not go to the point and does not clean the zone. In logs I can see following:

Additionaly, I've seen this warning:
```
Logger: custom_components.xiaomi_cloud_map_extractor.image_handler_v2
Source: custom_components/xiaomi_cloud_map_extractor/image_handler_v2.py:63
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 08:55:13 (199 occurrences)
Last logged: 09:11:44

unknown pixel_types: {62}
unknown pixel_types: {2, 62}
unknown pixel_types: {2, 61, 62}
unknown pixel_types: {2, 60, 61, 62}
```

Is there a chance that card should be adopted too?
If I use vacuum directly from the entity it's working fine.
BTW the number of `camera_thumbnail` warnings grows very quickly and can reach several hundred in 10 minutes.

**Comment by PiotrMachowski** [comment]
@HepoH3 map card is not adjusted to support Viomi vacuums yet

**Comment by vladeha** [comment]
Is it should work with Roidmi eve too?

I downloaded code from the branch and just changed row 173 to:
V2_MODELS = ['viomi.vacuum.v6', 'viomi.vacuum.v7', 'viomi.vacuum.v8','roidmi.vacuum.v60'],
but after restarting HA , got this error "zlib.error: Error -3 while decompressing data: incorrect header check"

**Comment by halfbakery** [comment]
I'm working on the unknown pixel types. My guess for the >= 60 values is rooms under cleanup. I've seen the value 2, but cannot figure out its meaning. Maybe some kind of obstackle. A new PR is in-progress :-)

**Comment by halfbakery** [comment]
Have someone seen unknown pixel_types messages since this update? The meaning of the pixel type #2 is still unknown. Could someone please report what is black on the map?

**Comment by HepoH3** [comment]
> 
> 
> Have someone seen unknown pixel_types messages since this update? The meaning of the pixel type 2 is still unknown. Could someone please report what is black (the default unknown pixel color) on the map?

Ty!
The 60+ values gone, the '2' value still unknown here the black part that I can see at the map, but currently I can't tell what it is

**Comment by Drafteed** [comment]
> Have someone seen unknown pixel_types messages since this update? The meaning of the pixel type 2 is still unknown. Could someone please report what is black (the default unknown pixel color) on the map?

chrome_2021-06-09_22-27-51

Here I have black carpets, where sometimes robot can give an error about the fall sensor. I guess the he thinks there is a cliff.

**Comment by halfbakery** [comment]
Ok, I've found the meaning behind the pixel type 2: previously undiscovered area (e.g. behind an open door and the wall, a removed flower or something else). Something the vacuum couldn't reach during the map creation.

**Pull request merged**
