### PR TITLE
Decouple image parser to an independent package

### PR DESCRIPTION
**Pull request by licheng5625**
Hello ,
thanks for your awsome project. 
Recently there is another project [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot) which can handle amost all the xiaomi devices including vacuums. It can handle the communication both miio (local) or miot (cloud) protocal. 

It is quite powerful, but unfortunately the map feature is missing. Your plugin and theirs both need connection to the xiaomi cloud. It makes the connection quite unstable. 

Since that project handles the miio and miot pretty well, so I created a [PR](https://github.com/al-one/hass-xiaomi-miot/pull/369), in where I introduced the very basic function from your project.

But I have to copy all image parser part to there manully. 

Do you feel if it makes sence that decouple all image parser part to a separate package ? And user can chose the data souce to feed the raw data .

Thank you

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
I don't think that this change would reduce connections to Xiaomi cloud as both integrations will probably need to download data from it anyway

**Comment by licheng5625** [comment]
> I don't think that this change would reduce connections to Xiaomi cloud as both integrations will probably need to download data from it anyway

You might be right. But that porject can focus on the connection protocals (login, miio command etc.)and supporting future models. The new independent package could be more focus on how to parser the raw data. 

This repo can be kept if user has only one xiaomi product (vacuum) at home, this plugin is lighter.

**Comment by PiotrMachowski** [comment]
By the way, have you tried reducing updates interval? It should greatly reduce connections to Xiaomi cloud
[documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#updates)

**Comment by licheng5625** [comment]
> 

Yes, but it is still a different connection with different token. Xiaomi server detected you have mutil connections at same time, they might disconnect time to time. 

I am still thinking to to decouple all the xiaomi devices connection, controling function into one plugin. Here we could more concentrate on how to parser the map data to image.

**Comment by PiotrMachowski** [comment]
The problem is that dependency on image parsers will increase in the future, as I plan to add some more image-related features. I think that I might extract image parser to a dedicated repo and create a pypi package, but I would prefer to do it after adding beforementioned features.

**Comment by licheng5625** [comment]
> 
sounds very promising.
I will close this PR, if you have another place could track the progress of the dedicated repo. Please kindly leave a link here.
Thank you very much.

**Pull request closed without merging**
